let myElement = document.getElementById('elzero');
console.log(myElement);
myElement = document.getElementsByTagName('div')[0];
console.log(myElement);
myElement = document.getElementsByName('js')[0];
console.log(myElement);
myElement = document.getElementsByClassName('element')[0];
console.log(myElement);
myElement = document.querySelector('#elzero');
console.log(myElement);
myElement = document.querySelector('.element');
console.log(myElement);
myElement = document.querySelector('[name = "js"]');
console.log(myElement);
myElement = document.querySelector('div');
console.log(myElement);
myElement = document.querySelectorAll('div')[0];
console.log(myElement);
myElement = document.querySelectorAll('.element')[0];
console.log(myElement);
myElement = document.querySelectorAll('#elzero')[0];
console.log(myElement);
myElement = document.querySelectorAll('[name = "js"]')[0];
console.log(myElement);
myElement = document.body.children[0];
console.log(myElement);
myElement = document.body.children[0];
console.log(myElement);
myElement = document.body.firstElementChild;
console.log(myElement);
myElement = document.body.childNodes[1];
console.log(myElement);
